[profile.default]
solc = '0.8.20'
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'seaport-sol/=lib/seaport-sol/src/',
    'seaport-types/=lib/seaport-types/src/',
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
